[package]
edition = "2021"
name = "day08"
version = "0.1.0"

[dependencies]
util = { path = "../util" }
anyhow = "1.0.75"
itertools = "0.12.0"
rxpect = "0.1.1"
regex = "1.10.2"
num-integer = "0.1.45"
